// GENERATED by assets/make-logo.py. Do not edit; regenerate.
//
// The Omashift wordmark, and the H is not a letter. It is the channel a gearbox
// lever moves through, and the lever runs a real H pattern: up left for first,
// down through neutral for second, across the neutral rail, up right for third,
// down for fourth. It moves THROUGH neutral rather than across the crossbar,
// because getting that wrong is visible to exactly the people the pun is aimed
// at.
//
// This is attract mode. It belongs on the screen shown while the player's own
// keybindings are still live and the game is waiting, and it must never be
// something anyone has to sit through: nothing here delays a keypress.

import QtQuick

Item {
    id: wordmark

    property color ink: "#F3F19A"
    /// Height of one grid cell. The whole mark is 10 cells tall plus a
    /// 15 unit margin, so this is the only size anyone has to pick.
    property real cell: 24

    readonly property real designWidth: 1302
    readonly property real designHeight: 270
    readonly property real k: cell / 24

    implicitWidth: designWidth * k
    implicitHeight: designHeight * k

    Item {
        width: wordmark.designWidth
        height: wordmark.designHeight
        transform: Scale { xScale: wordmark.k; yScale: wordmark.k }

        Repeater {
            model: [
            [38.6, 14.6, 96.8, 24.8],
            [14.6, 38.6, 144.8, 24.8],
            [14.6, 62.6, 48.8, 24.8],
            [110.6, 62.6, 48.8, 24.8],
            [14.6, 86.6, 48.8, 24.8],
            [110.6, 86.6, 48.8, 24.8],
            [14.6, 110.6, 48.8, 24.8],
            [110.6, 110.6, 48.8, 24.8],
            [14.6, 134.6, 48.8, 24.8],
            [110.6, 134.6, 48.8, 24.8],
            [14.6, 158.6, 48.8, 24.8],
            [110.6, 158.6, 48.8, 24.8],
            [14.6, 182.6, 48.8, 24.8],
            [110.6, 182.6, 48.8, 24.8],
            [14.6, 206.6, 144.8, 24.8],
            [38.6, 230.6, 96.8, 24.8],
            [206.6, 14.6, 144.8, 24.8],
            [182.6, 38.6, 192.8, 24.8],
            [182.6, 62.6, 48.8, 24.8],
            [254.6, 62.6, 48.8, 24.8],
            [326.6, 62.6, 48.8, 24.8],
            [182.6, 86.6, 48.8, 24.8],
            [254.6, 86.6, 48.8, 24.8],
            [326.6, 86.6, 48.8, 24.8],
            [182.6, 110.6, 48.8, 24.8],
            [254.6, 110.6, 48.8, 24.8],
            [326.6, 110.6, 48.8, 24.8],
            [182.6, 134.6, 48.8, 24.8],
            [254.6, 134.6, 48.8, 24.8],
            [326.6, 134.6, 48.8, 24.8],
            [182.6, 158.6, 48.8, 24.8],
            [254.6, 158.6, 48.8, 24.8],
            [326.6, 158.6, 48.8, 24.8],
            [182.6, 182.6, 48.8, 24.8],
            [254.6, 182.6, 48.8, 24.8],
            [326.6, 182.6, 48.8, 24.8],
            [182.6, 206.6, 48.8, 24.8],
            [254.6, 206.6, 48.8, 24.8],
            [326.6, 206.6, 48.8, 24.8],
            [182.6, 230.6, 48.8, 24.8],
            [254.6, 230.6, 48.8, 24.8],
            [326.6, 230.6, 48.8, 24.8],
            [422.6, 14.6, 96.8, 24.8],
            [398.6, 38.6, 144.8, 24.8],
            [398.6, 62.6, 48.8, 24.8],
            [494.6, 62.6, 48.8, 24.8],
            [398.6, 86.6, 48.8, 24.8],
            [494.6, 86.6, 48.8, 24.8],
            [398.6, 110.6, 144.8, 24.8],
            [398.6, 134.6, 144.8, 24.8],
            [398.6, 158.6, 48.8, 24.8],
            [494.6, 158.6, 48.8, 24.8],
            [398.6, 182.6, 48.8, 24.8],
            [494.6, 182.6, 48.8, 24.8],
            [398.6, 206.6, 48.8, 24.8],
            [494.6, 206.6, 48.8, 24.8],
            [398.6, 230.6, 48.8, 24.8],
            [494.6, 230.6, 48.8, 24.8],
            [590.6, 14.6, 96.8, 24.8],
            [566.6, 38.6, 144.8, 24.8],
            [566.6, 62.6, 48.8, 24.8],
            [566.6, 86.6, 48.8, 24.8],
            [566.6, 110.6, 144.8, 24.8],
            [566.6, 134.6, 144.8, 24.8],
            [662.6, 158.6, 48.8, 24.8],
            [662.6, 182.6, 48.8, 24.8],
            [566.6, 206.6, 144.8, 24.8],
            [590.6, 230.6, 96.8, 24.8],
            [734.6, 14.6, 48.8, 12.8],
            [830.6, 14.6, 48.8, 12.8],
            [734.6, 26.6, 48.8, 12.8],
            [830.6, 26.6, 48.8, 12.8],
            [734.6, 38.6, 12.8, 12.8],
            [770.6, 38.6, 12.8, 12.8],
            [830.6, 38.6, 12.8, 12.8],
            [866.6, 38.6, 12.8, 12.8],
            [734.6, 50.6, 12.8, 12.8],
            [770.6, 50.6, 12.8, 12.8],
            [830.6, 50.6, 12.8, 12.8],
            [866.6, 50.6, 12.8, 12.8],
            [734.6, 62.6, 12.8, 12.8],
            [770.6, 62.6, 12.8, 12.8],
            [830.6, 62.6, 12.8, 12.8],
            [866.6, 62.6, 12.8, 12.8],
            [734.6, 74.6, 12.8, 12.8],
            [770.6, 74.6, 12.8, 12.8],
            [830.6, 74.6, 12.8, 12.8],
            [866.6, 74.6, 12.8, 12.8],
            [734.6, 86.6, 12.8, 12.8],
            [770.6, 86.6, 12.8, 12.8],
            [830.6, 86.6, 12.8, 12.8],
            [866.6, 86.6, 12.8, 12.8],
            [734.6, 98.6, 12.8, 12.8],
            [770.6, 98.6, 12.8, 12.8],
            [830.6, 98.6, 12.8, 12.8],
            [866.6, 98.6, 12.8, 12.8],
            [734.6, 110.6, 12.8, 12.8],
            [770.6, 110.6, 72.8, 12.8],
            [866.6, 110.6, 12.8, 12.8],
            [734.6, 122.6, 12.8, 12.8],
            [866.6, 122.6, 12.8, 12.8],
            [734.6, 134.6, 12.8, 12.8],
            [866.6, 134.6, 12.8, 12.8],
            [734.6, 146.6, 12.8, 12.8],
            [770.6, 146.6, 72.8, 12.8],
            [866.6, 146.6, 12.8, 12.8],
            [734.6, 158.6, 12.8, 12.8],
            [770.6, 158.6, 12.8, 12.8],
            [830.6, 158.6, 12.8, 12.8],
            [866.6, 158.6, 12.8, 12.8],
            [734.6, 170.6, 12.8, 12.8],
            [770.6, 170.6, 12.8, 12.8],
            [830.6, 170.6, 12.8, 12.8],
            [866.6, 170.6, 12.8, 12.8],
            [734.6, 182.6, 12.8, 12.8],
            [770.6, 182.6, 12.8, 12.8],
            [830.6, 182.6, 12.8, 12.8],
            [866.6, 182.6, 12.8, 12.8],
            [734.6, 194.6, 12.8, 12.8],
            [770.6, 194.6, 12.8, 12.8],
            [830.6, 194.6, 12.8, 12.8],
            [866.6, 194.6, 12.8, 12.8],
            [734.6, 206.6, 12.8, 12.8],
            [770.6, 206.6, 12.8, 12.8],
            [830.6, 206.6, 12.8, 12.8],
            [866.6, 206.6, 12.8, 12.8],
            [734.6, 218.6, 12.8, 12.8],
            [770.6, 218.6, 12.8, 12.8],
            [830.6, 218.6, 12.8, 12.8],
            [866.6, 218.6, 12.8, 12.8],
            [734.6, 230.6, 48.8, 12.8],
            [830.6, 230.6, 48.8, 12.8],
            [734.6, 242.6, 48.8, 12.8],
            [830.6, 242.6, 48.8, 12.8],
            [902.6, 14.6, 48.8, 24.8],
            [902.6, 38.6, 48.8, 24.8],
            [902.6, 62.6, 48.8, 24.8],
            [902.6, 86.6, 48.8, 24.8],
            [902.6, 110.6, 48.8, 24.8],
            [902.6, 134.6, 48.8, 24.8],
            [902.6, 158.6, 48.8, 24.8],
            [902.6, 182.6, 48.8, 24.8],
            [902.6, 206.6, 48.8, 24.8],
            [902.6, 230.6, 48.8, 24.8],
            [998.6, 14.6, 96.8, 24.8],
            [974.6, 38.6, 144.8, 24.8],
            [974.6, 62.6, 48.8, 24.8],
            [974.6, 86.6, 48.8, 24.8],
            [974.6, 110.6, 120.8, 24.8],
            [974.6, 134.6, 120.8, 24.8],
            [974.6, 158.6, 48.8, 24.8],
            [974.6, 182.6, 48.8, 24.8],
            [974.6, 206.6, 48.8, 24.8],
            [974.6, 230.6, 48.8, 24.8],
            [1166.6, 14.6, 96.8, 24.8],
            [1142.6, 38.6, 144.8, 24.8],
            [1190.6, 62.6, 48.8, 24.8],
            [1190.6, 86.6, 48.8, 24.8],
            [1190.6, 110.6, 48.8, 24.8],
            [1190.6, 134.6, 48.8, 24.8],
            [1190.6, 158.6, 48.8, 24.8],
            [1190.6, 182.6, 48.8, 24.8],
            [1190.6, 206.6, 48.8, 24.8],
            [1190.6, 230.6, 48.8, 24.8]
            ]
            Rectangle {
                required property var modelData
                x: modelData[0]; y: modelData[1]
                width: modelData[2]; height: modelData[3]
                color: wordmark.ink
            }
        }

        Rectangle {
            id: knob
            property real cx: 759
            property real cy: 135
            width: 33.6; height: 33.6
            radius: 16.8
            x: cx - 16.8
            y: cy - 16.8
            color: wordmark.ink

            SequentialAnimation {
                running: wordmark.visible
                loops: Animation.Infinite
            PauseAnimation { duration: 450 }
            ParallelAnimation {
                NumberAnimation { target: knob; property: "cx"; to: 759; duration: 220; easing.type: Easing.InOutQuad }
                NumberAnimation { target: knob; property: "cy"; to: 63; duration: 220; easing.type: Easing.InOutQuad }
            }
            PauseAnimation { duration: 550 }
            ParallelAnimation {
                NumberAnimation { target: knob; property: "cx"; to: 759; duration: 220; easing.type: Easing.InOutQuad }
                NumberAnimation { target: knob; property: "cy"; to: 135; duration: 220; easing.type: Easing.InOutQuad }
            }
            PauseAnimation { duration: 100 }
            ParallelAnimation {
                NumberAnimation { target: knob; property: "cx"; to: 759; duration: 220; easing.type: Easing.InOutQuad }
                NumberAnimation { target: knob; property: "cy"; to: 207; duration: 220; easing.type: Easing.InOutQuad }
            }
            PauseAnimation { duration: 550 }
            ParallelAnimation {
                NumberAnimation { target: knob; property: "cx"; to: 759; duration: 220; easing.type: Easing.InOutQuad }
                NumberAnimation { target: knob; property: "cy"; to: 135; duration: 220; easing.type: Easing.InOutQuad }
            }
            PauseAnimation { duration: 200 }
            ParallelAnimation {
                NumberAnimation { target: knob; property: "cx"; to: 855; duration: 220; easing.type: Easing.InOutQuad }
                NumberAnimation { target: knob; property: "cy"; to: 135; duration: 220; easing.type: Easing.InOutQuad }
            }
            PauseAnimation { duration: 200 }
            ParallelAnimation {
                NumberAnimation { target: knob; property: "cx"; to: 855; duration: 220; easing.type: Easing.InOutQuad }
                NumberAnimation { target: knob; property: "cy"; to: 63; duration: 220; easing.type: Easing.InOutQuad }
            }
            PauseAnimation { duration: 550 }
            ParallelAnimation {
                NumberAnimation { target: knob; property: "cx"; to: 855; duration: 220; easing.type: Easing.InOutQuad }
                NumberAnimation { target: knob; property: "cy"; to: 135; duration: 220; easing.type: Easing.InOutQuad }
            }
            PauseAnimation { duration: 100 }
            ParallelAnimation {
                NumberAnimation { target: knob; property: "cx"; to: 855; duration: 220; easing.type: Easing.InOutQuad }
                NumberAnimation { target: knob; property: "cy"; to: 207; duration: 220; easing.type: Easing.InOutQuad }
            }
            PauseAnimation { duration: 550 }
            ParallelAnimation {
                NumberAnimation { target: knob; property: "cx"; to: 855; duration: 220; easing.type: Easing.InOutQuad }
                NumberAnimation { target: knob; property: "cy"; to: 135; duration: 220; easing.type: Easing.InOutQuad }
            }
            PauseAnimation { duration: 200 }
            ParallelAnimation {
                NumberAnimation { target: knob; property: "cx"; to: 759; duration: 220; easing.type: Easing.InOutQuad }
                NumberAnimation { target: knob; property: "cy"; to: 135; duration: 220; easing.type: Easing.InOutQuad }
            }
            PauseAnimation { duration: 550 }
            }
        }
    }
}
